version: '3.8'

services:
  # Backend Spring Boot Service - Development
  app:
    build: .
    container_name: culinary-atlas-app-dev
    restart: unless-stopped
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}" 
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - culinary-network-dev
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${SERVER_PORT}/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s 

  # PostgreSQL Database Service - Development
  db:
    image: postgres:14-alpine
    container_name: culinary-atlas-db-dev
    restart: unless-stopped
    ports:
      - "${DB_PORT}:${DB_PORT}"  
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: danangatlasculinarydb_dev
    volumes:
      - db-data-dev:/var/lib/postgresql/data
    networks:
      - culinary-network-dev
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data-dev:

networks:
  culinary-network-dev:
    driver: bridge