version: '3.8'

services:
  # Backend Spring Boot Service - Production
  app:
    build: .
    container_name: culinary-atlas-app-prod
    restart: unless-stopped
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"  
    env_file:
      - .env
    networks:
      - culinary-network-prod
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${SERVER_PORT}/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s 

networks:
  culinary-network-prod:
    driver: bridge