name: Reusable Confirmation Step

on:
  workflow_call:

jobs:
  manual-approval:
    runs-on: ubuntu-latest
    environment: 
      name: development
    steps:
      - name: Awaiting approval for development deployment
        run: echo "Please review and approve the deployment to development."