name: Reusable Confirmation Step

on:
  workflow_call:

jobs:
  manual-approval:
    runs-on: ubuntu-latest
    environment: 
      name: production
    steps:
      - name: Awaiting approval for production deployment
        run: echo "Please review and approve the deployment to production."